### ISSUE TITLE
Notifications accumulate in indicator

### ISSUE THREAD

**Issue by janxkoci** [elementary/wingpanel-indicator-notifications#115]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Some weeks ago there was an apparent change in the behavior of my notifications, without me changing any settings, so I think it's a bug. All notifications end up in the indicator list, regardless if I interact with them or not - even if I click notification to open an app (this works with some apps sometimes, like AppCenter, Files, or Mail), the notification will still hang out in the notification indicator later. Same for chat apps (made with Webpin) or any other. Every day I find old notifications collected there, for emails I already replied to or updates I already installed.

### To Reproduce
1. Trigger a notification (e.g. copy a file in Files and unfocus the app, i.e. switch focus to other app)
2. Click the notification bubble that appears to focus the app again
3. Look at the notification indicator - there is a bange
4. Open indicator - the notification is there

### Expected behavior
After interacting with notification bubble, it should not land in the indicator.

## Platform Information

This happens on multiple laptops, here is one:

![Snímek z 2020-05-21 09-35-25](https://user-images.githubusercontent.com/19331850/82534984-715a9800-9b46-11ea-9d25-6c8b445d9978.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by Rantyrant** [comment]
Not sure if this is related and should be seperate bug or even if it's intended, but:

Notifications used to clear automatically if you focused the app that had a notification. 
Example of use before: Terminal completes an action like apt update while unfocused. It has a message about the completed action in the notification center, but the message in the notification center cleared automatically if you focused the app in question, even if you didn't open the notification center.

Now the messages stay, even though you focused the app.

**Comment by janxkoci** [comment]
Well for me all notifications get into the indicator and stay there, until I explicitly clear them with one of the buttons in the indicator. I currently see no other way to clear them, as was the case in the past. So I think your case is part of the bug I'm describing here.

**Comment by guiscaranse** [comment]
I am also having a similar issue, I don't even care a lot about notifications being accumulated on the indicator, the problem is if it accumulates a lot of notifications it gets slow and crashes. Maybe allow users to set a lifespan for notifications?

**Comment by janxkoci** [comment]
I think it should **do the right thing** - if I interact with a notification, don't put it in the drawer in indicator and instead clear it. You know, like your phone does.

**Comment by joe733** [comment]
Yea, I was just about to open an issue: "Forget old notifications"

![Screenshot from 2020-04-10 17-33-39](https://user-images.githubusercontent.com/38415384/83908395-af7dcb80-a784-11ea-8f7d-63f214bfc220.png)

This behaviour is persistent across restarts.

**Comment by JMoerman** [comment]
Even if an app withdraws a notification, or replaces a notification the old notification remains. It seems like the latter will get fixed when this lands: https://github.com/elementary/wingpanel-indicator-notifications/pull/135

**Comment by danirabbit** [comment]
Replaces is now supported, so closing in favor of #204 and #228 which are more specific

**Comment by janxkoci** [comment]
This bug was mostly about notifications that should never end up in the indicator, which is still happening on my machine. The other reports don't mention such issue at all 😕

**Comment by Marukesu** [comment]
> This bug was mostly about notifications that should never end up in the indicator (e.g. when I click on them and open the app, or when I disable indicator notifications per app in the settings)…

The first case was fixed in #243 (available since version 7.0 of the indicator), the second case in elementary/notifications#211 (available since version 7.0.1 or the server).

**Comment by janxkoci** [comment]
How do I find the version of an indicator? I cannot find any in the Appcenter.

And I have these settings but I still see Appcenter updates in the indicator every day:

![Snímky obrazovky pořízený 2023-08-31 18 36 29](https://github.com/elementary/wingpanel-indicator-notifications/assets/19331850/c898fa97-4e67-43f8-8496-5270d63d1662)

**Comment by Marukesu** [comment]
> How do I find the version of an indicator? I cannot find any in the Appcenter.

You can use `dpkg-query -Wf '${Version}\n' wingpanel-indicator-notifications`.

> And I have these settings but I still see Appcenter updates in the indicator every day

i cannot reproduce this here, can you look at the contents of `gsettings list-recursively io.elementary.notifications.applications:/io/elementary/notifications/applications/appcenter/` and check that `remember` is set to `false`, also, if there's isn't a cached appcenter notification in `$XDG_CACHE_HOME/.notifications.session`.

**Comment by janxkoci** [comment]
@Marukesu Ah, that's the package name? I expected RDNN so I was looking for `io.elementary.wingpanel*` :sweat_smile: 

My version is `7.0.0+r843+pkg35~ubuntu7.1`.

```
$ gsettings list-recursively io.elementary.notifications.applications:/io/elementary/notifications/applications/appcenter/
io.elementary.notifications.applications ask true
io.elementary.notifications.applications bubbles true
io.elementary.notifications.applications remember true
io.elementary.notifications.applications sounds true
```

and

```
$ $XDG_CACHE_HOME/.notifications.session
bash: /.notifications.session: Adresář nebo soubor neexistuje
```

Translation: "Directory or file does not exist"

**Comment by janxkoci** [comment]
After the latest batch of updates and several reboots, I no longer see Appcenter notifications in the indicator. I will keep watching it and report back if I see something out of line.
