### ISSUE TITLE
Spotify and Telegram notifications listed under 'Other'

### ISSUE THREAD

**Issue by pthrrr** [elementary/wingpanel-indicator-notifications#193]
## What Happened

I have installed the Spotify and Telegram client from Flathub using Sideload.
In the notification center, notifications from both apps are grouped under the category 'others' (in the screenshot 'Andere').

![notification](https://user-images.githubusercontent.com/29637548/116918887-082d4100-ac40-11eb-9e6f-c3fdb063bf24.png)
Notifications 1,2,4 are from Spotify, 3 from Telegram

![settings](https://user-images.githubusercontent.com/29637548/116918889-08c5d780-ac40-11eb-9451-6c3a57300463.png)
In notification settings, both apps are recognized correctly. However, the notification settings made on the individual app has no effects.

## Expected Behavior

Notifications from Telegram should be listed under a group called 'Telegram'.
Notifications from Spotify should be listed under a group called 'Spotify'.

## Steps to Reproduce

1. Go to [flathub.org ](https://www.flathub.org) and look for Spotify, Telegram
2. Install apps with Sideload
3. Play music with Spotify and wait for the track to change. Receive some Telegram notifications.

## Platform Information

System: elementary OS 6 Early Access (Public Beta)
Telegram Desktop: 2.7.4 | stable | flathub | user
Spotify: 1.1.55.498.gf9a83c60 | stable | flathub | user

**Comment by danrabbit** [comment]
This was likely fixed in #190

**Comment by danrabbit** [comment]
A possible fix for this should now be built and available as an update. Old notifications will stay where they are, but new notifications should now be correctly categorized. Closing this issue as fixed.

If you are still able to reproduce the issue, please comment and we can reopen the report

**Comment by pierrefabarius** [comment]
Thank you Daniel. I still encounter the bug. 
I updated all packages and reinstalled spotify, but it did not help.

- wingpanel version 2.3.2
- notifications indicator 2.1.4

Please me know if there is else anything you need.

**Comment by pierrefabarius** [comment]
This is what happens now with telegram.

![notification1](https://user-images.githubusercontent.com/29637548/118331868-81af1400-b509-11eb-9373-5b68eaa61b77.png)
Incoming notifications show the correct icon.

![notification2](https://user-images.githubusercontent.com/29637548/118331869-8247aa80-b509-11eb-8530-f82e50025a03.png)
In the notification center the generic icon is displayed.

Spotify still only shows the generic icon.

**Comment by krcx** [comment]
Hi. I also encountered this problem. I am using 5.1.7, and I edited some apps' files to have them separated notification settings by adding `X-GNOME-UsesNotifications=true` to the *.desktop file.

They showed up separately under the notification settings, 
![image](https://user-images.githubusercontent.com/66221307/118408904-6b7f9000-b690-11eb-8f84-c052b4ddbae7.png)

but their notifications are still showing and behaving under ""Other" section like this.
![image](https://user-images.githubusercontent.com/66221307/118408887-530f7580-b690-11eb-9bb9-4cc9acdb5ee0.png)

**Comment by bluesabre** [comment]
It appears that Spotify doesn't send the `desktop-entry` hint with its notifications, making it difficult to reliably identify. Instead, I'm only seeing `icon_data`, `image-data`, and `urgency`.

Using all of the available information, we could potentially get back to the desktop entry from the Dbus sender, but I think that's going too far.

```
Bus Name (sender): :1.703

app_name: Spotify
app_icon: 
summary: drivers license
body: Olivia Rodrigo - drivers license

hint: icon_data, (iiibiiay)
hint: urgency, y
hint: image-data, (iiibiiay)
```

com.spotify.Client 1.1.55.498.gf9a83c60 from flathub.

**Comment by davidmhewitt** [comment]
I've just had a look at Spotify from flathub. It makes a hole in the sandbox to talk directly to the `org.freedesktop.Notifications` bus. Properly sandbox aware applications wouldn't need to do this, and would instead send the notification to the notification portal, and that would be aware of which flatpak had sent the notification and properly include the `desktop-entry` in the call to the system's notification server.

I imagine this is because Spotify is an Electron app and Electron (probably) doesn't support sending notifications via a Flatpak portal, whereas GTK and Qt apps do this automatically.

If I remember correctly, the fact that Electron applications don't send a `desktop-entry` was fixed here: https://github.com/electron/electron/pull/12192 . So this specific case is probably an issue with Spotify not using a recent enough version of Electron.

**Comment by Eldhrimer** [comment]
>It makes a hole in the sandbox to talk directly to the `org.freedesktop.Notifications` bus. Properly sandbox aware applications wouldn't need to do this, and would instead send the notification to the notification portal...
> 
> I imagine this is because Spotify is an Electron app and Electron (probably) doesn't support sending notifications via a Flatpak portal, whereas GTK and Qt apps do this automatically.

I took a quick look through my installed flathub apps, and all of them do this. Here is a list of what I've got installed:

- Firefox
- Remmina
- Discord
- Telegram
- Athenaeum
- Github-desktop

There was also an appcenter app that did the same, Hourglass.

I think this behavior while not intended it's kind of a common practice in flathub, and should be taken into account to display appropiate notifications.

**Comment by cedewey** [comment]
I've filed a bug in Spotify's Help Forum for this. If people upvote it, it might help bring it to Spotify's attention.

https://community.spotify.com/t5/Desktop-Linux/Desktop-Notification-Settings-Not-Working/m-p/5321539#M20898

**Comment by danirabbit** [comment]
Gonna close this since applications need to be using the proper notification portal and punching a sandbox hole to talk directly to the server is what causes these issues. There's nothing we can do to fix apps who don't use the API properly
